### ISSUE TITLE
Bad installation path

### ISSUE THREAD

**Issue by hopeseekr** [longlong2010/hhvm-gearman#7]
Whenever I run `make install`, CMake installs the `gearman.so` into **/usr/lib64/hhvm/extensions/20150212/gearman.so**, however, the correct extension directory, also found by CMake, is 

`HHVM_DYNAMIC_EXTENSION_DIR="/usr/lib64/hhvm/extensions"`

**Expected result:** The installation should occur in the system-specified HHVM extension directory, without a date prefix.

**Comment by longlong2010** [comment]
Please reference 
https://docs.hhvm.com/hhvm/extensions/introduction

**Comment by hopeseekr** [comment]
@longlong2010 Thank you. I really used this project while I had my corporation using HHVM instead of PHP. 

So sad that Facebook gave up being a co-steward of the PHP language.
